deployment:
  tasks:
    - run: export DEPLOYPATH="/home1/spreaeb3/public_html/website_d6ddc397"
    - run: mkdir -p "$DEPLOYPATH"
    - run: rsync -a --delete --exclude='.git' --exclude='.cpanel.yml' . "$DEPLOYPATH/"
    - run: find "$DEPLOYPATH" -type d -exec chmod 755 {} \;
    - run: find "$DEPLOYPATH" -type f -exec chmod 644 {} \;
    - run: chown -R "spreaeb3":"spreaeb3" "$DEPLOYPATH"
